### ISSUE TITLE
getting 403 error when bootstrapping with this cookbook 

### ISSUE THREAD

**Issue by bixu** [chef-cookbooks/ark#108] opened 2015-05-22 11:38 UTC
This is on Ubuntu 14.04

```
Recipe: maven::default
  * ark[maven] action install
    * directory[/usr/local/maven-3.1.1] action create
      - create new directory /usr/local/maven-3.1.1
    * remote_file[/var/chef/cache/maven-3.1.1.tar.gz] action create
      - create new file /var/chef/cache/maven-3.1.1.tar.gz
      - update content in file /var/chef/cache/maven-3.1.1.tar.gz from none to 077ed4
      (new content is binary, diff output suppressed)
    * execute[unpack /var/chef/cache/maven-3.1.1.tar.gz] action nothing (skipped due to action :nothing)
    * execute[set owner on /usr/local/maven-3.1.1] action nothing (skipped due to action :nothing)
    * link[/usr/local/maven] action create
      - create symlink at /usr/local/maven to /usr/local/maven-3.1.1
    * template[/etc/profile.d/maven.sh] action create

      ================================================================================
      Error executing action `create` on resource 'template[/etc/profile.d/maven.sh]'
      ================================================================================

      Net::HTTPServerException
      ------------------------
      403 "Forbidden"

      Resource Declaration:
      ---------------------
      # In /var/chef/cache/cookbooks/ark/providers/default.rb

       85:     template "/etc/profile.d/#{new_resource.name}.sh" do
       86:       cookbook 'ark'
       87:       source 'add_to_path.sh.erb'
       88:       owner 'root'
       89:       group 'root'
       90:       mode '0755'
       91:       cookbook 'ark'
       92:       variables(:directory => "#{new_resource.path}/bin")
       93:       only_if { new_resource.append_env_path }
       94:     end
       95:   end

      Compiled Resource:
      ------------------
      # Declared in /var/chef/cache/cookbooks/ark/providers/default.rb:85:in `block in class_from_file'

      template("/etc/profile.d/maven.sh") do
        provider Chef::Provider::Template
        action "create"
        retries 0
        retry_delay 2
        guard_interpreter :default
        path "/etc/profile.d/maven.sh"
        backup 5
        atomic_update true
        source "add_to_path.sh.erb"
        cookbook "ark"
        variables {:directory=>"/usr/local/maven-3.1.1/bin"}
        cookbook_name "maven"
        mode "0755"
        owner "root"
        group "root"
        only_if { #code block }
      end

    * execute[unpack /var/chef/cache/maven-3.1.1.tar.gz] action run
      - execute /bin/tar xzf /var/chef/cache/maven-3.1.1.tar.gz --strip-components=1
    * execute[set owner on /usr/local/maven-3.1.1] action run
      - execute chown -R root:0 /usr/local/maven-3.1.1

    ================================================================================
    Error executing action `install` on resource 'ark[maven]'
    ================================================================================

    Net::HTTPServerException
    ------------------------
    template[/etc/profile.d/maven.sh] (/var/chef/cache/cookbooks/ark/providers/default.rb line 85) had an error: Net::HTTPServerException: 403 "Forbidden"

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/maven/recipes/default.rb

     28: ark 'maven' do
     29:   url             node['maven'][mvn_version]['url']
     30:   checksum        node['maven'][mvn_version]['checksum']
     31:   home_dir        node['maven']['m2_home']
     32:   win_install_dir node['maven']['m2_home']
     33:   version         node['maven'][mvn_version]['version']
     34:   append_env_path true
     35: end
     36:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/maven/recipes/default.rb:28:in `from_file'

    ark("maven") do
      provider Chef::Provider::Ark
      action :install
      updated true
      updated_by_last_action true
      retries 0
      retry_delay 2
      guard_interpreter :default
      cookbook_name "maven"
      recipe_name "default"
      url "http://apache.mirrors.tds.net/maven/maven-3/3.1.1/binaries/apache-maven-3.1.1-bin.tar.gz"
      checksum "077ed466455991d5abb4748a1d022e2d2a54dc4d557c723ecbacdc857c61d51b"
      home_dir "/usr/local/maven"
      win_install_dir "/usr/local/maven"
      version "3.1.1"
      append_env_path true
      extension "tar.gz"
      prefix_bin "/usr/local/bin"
      path "/usr/local/maven-3.1.1"
      release_file "/var/chef/cache/maven-3.1.1.tar.gz"
      strip_components 1
      owner "root"
      group 0
    end

Recipe: postfix::_common
  * service[postfix] action restart
    - restart service service[postfix]
Recipe: postfix::transports
  * execute[update-postfix-transport] action run
    - execute postmap /etc/postfix/transport
Recipe: openssh::default
  * service[ssh] action restart
    - restart service service[ssh]
Recipe: chef-client::init_service
  * service[chef-client] action restart
    - restart service service[chef-client]

Running handlers:
[2015-05-22T10:59:24+00:00] ERROR: Running exception handlers
Running handlers complete
[2015-05-22T10:59:24+00:00] ERROR: Exception handlers complete
[2015-05-22T10:59:24+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 182 resources updated in 4813.32478806 seconds
[2015-05-22T10:59:26+00:00] ERROR: ark[maven] (maven::default line 28) had an error: Net::HTTPServerException: template[/etc/profile.d/maven.sh] (/var/chef/cache/cookbooks/ark/providers/default.rb line 85) had an error: Net::HTTPServerException: 403 "Forbidden"
[2015-05-22T10:59:28+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by cheeseplus** [comment] 2016-12-26 14:24
This appears to be a transient error or something related to local network conditions as I can't reproduce the 403. Closing.

**Closed by cheeseplus** 2016-12-26 14:24 UTC
