### ISSUE TITLE
The default value ('root') of the owner attribute is not appropriate for Windows platform.

### ISSUE THREAD

**Issue by buri17** [chef-cookbooks/ark#150] opened 2016-05-28 01:41 UTC
On windows platform, the 'root' user does not exist by default.

I was able to fix by changing ark/resources/default.rb as follows:

``` ruby
attribute :owner, kind_of: String, default: case node['platform_family']
                                            when 'windows'
                                              'Administrator'
                                            else
                                              'root'
                                            end
```

However, I'm not sure if the above fix is appropriate for the current design.

It seems that some platform-dependent default value is implemented in ark/libraries/resource_default.rb.

**Comment by tas50** [comment] 2016-12-06 19:11
Dupe of #168

**Closed by tas50** 2016-12-06 19:11 UTC
